gg_snd_HarpyYes1 = nil
gg_snd_SkeletonYes1 = nil
gg_snd_Hint = nil
gg_snd_NightElfX1 = ""
gg_snd_Orc3 = ""
gg_snd_UndeadX1 = ""
gg_snd_Human2 = ""
gg_snd_GoodJob = nil
gg_trg_InitLua = nil
function InitGlobals()
end

function InitSounds()
gg_snd_HarpyYes1 = CreateSound("Units\\Creeps\\Harpy\\HarpyYes1.wav", false, true, true, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_HarpyYes1, 853)
SetSoundChannel(gg_snd_HarpyYes1, 0)
SetSoundVolume(gg_snd_HarpyYes1, -1)
SetSoundPitch(gg_snd_HarpyYes1, 1.0)
SetSoundDistances(gg_snd_HarpyYes1, 0.0, 10000.0)
SetSoundDistanceCutoff(gg_snd_HarpyYes1, 3000.0)
SetSoundConeAngles(gg_snd_HarpyYes1, 0.0, 0.0, 127)
SetSoundConeOrientation(gg_snd_HarpyYes1, 0.0, 0.0, 0.0)
gg_snd_SkeletonYes1 = CreateSound("Units\\Undead\\Skeleton\\SkeletonYes1.wav", false, true, true, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_SkeletonYes1, 2785)
SetSoundChannel(gg_snd_SkeletonYes1, 0)
SetSoundVolume(gg_snd_SkeletonYes1, -1)
SetSoundPitch(gg_snd_SkeletonYes1, 1.0)
SetSoundDistances(gg_snd_SkeletonYes1, 0.0, 10000.0)
SetSoundDistanceCutoff(gg_snd_SkeletonYes1, 3000.0)
SetSoundConeAngles(gg_snd_SkeletonYes1, 0.0, 0.0, 127)
SetSoundConeOrientation(gg_snd_SkeletonYes1, 0.0, 0.0, 0.0)
gg_snd_Hint = CreateSound("Sound\\Interface\\Hint.wav", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Hint, 2845)
SetSoundChannel(gg_snd_Hint, 0)
SetSoundVolume(gg_snd_Hint, -1)
SetSoundPitch(gg_snd_Hint, 1.0)
gg_snd_NightElfX1 = "Sound\\Music\\mp3Music\\NightElfX1.mp3"
gg_snd_Orc3 = "Sound\\Music\\mp3Music\\Orc3.mp3"
gg_snd_UndeadX1 = "Sound\\Music\\mp3Music\\UndeadX1.mp3"
gg_snd_Human2 = "Sound\\Music\\mp3Music\\Human2.mp3"
gg_snd_GoodJob = CreateSound("Sound\\Interface\\GoodJob.wav", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_GoodJob, 2954)
SetSoundChannel(gg_snd_GoodJob, 0)
SetSoundVolume(gg_snd_GoodJob, -1)
SetSoundPitch(gg_snd_GoodJob, 1.0)
end

function CreateBuildingsForPlayer0()
local p = Player(0)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("htow"), -12992.0, 11392.0, 270.000, FourCC("htow"))
end

function CreateUnitsForPlayer0()
local p = Player(0)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("U004"), -8664.9, 5833.5, 177.083, FourCC("U004"))
u = BlzCreateUnitWithSkin(p, FourCC("U005"), -8394.5, 5909.5, 72.424, FourCC("U005"))
u = BlzCreateUnitWithSkin(p, FourCC("U004"), -4014.2, 6658.3, 18.029, FourCC("U004"))
u = BlzCreateUnitWithSkin(p, FourCC("U004"), -4139.9, 6290.7, 263.262, FourCC("U004"))
u = BlzCreateUnitWithSkin(p, FourCC("U004"), -3696.5, 6657.5, 316.273, FourCC("U004"))
u = BlzCreateUnitWithSkin(p, FourCC("U004"), -3717.0, 5769.7, 62.042, FourCC("U004"))
u = BlzCreateUnitWithSkin(p, FourCC("U004"), -4336.9, 6601.3, 62.679, FourCC("U004"))
u = BlzCreateUnitWithSkin(p, FourCC("U007"), -4088.3, 6508.7, 64.810, FourCC("U007"))
u = BlzCreateUnitWithSkin(p, FourCC("U006"), -4159.1, 5987.9, 127.017, FourCC("U006"))
u = BlzCreateUnitWithSkin(p, FourCC("U006"), -3373.1, 6306.4, 302.749, FourCC("U006"))
u = BlzCreateUnitWithSkin(p, FourCC("U006"), -4304.0, 6808.8, 335.884, FourCC("U006"))
end

function CreatePlayerBuildings()
CreateBuildingsForPlayer0()
end

function CreatePlayerUnits()
CreateUnitsForPlayer0()
end

function CreateAllUnits()
CreatePlayerBuildings()
CreatePlayerUnits()
end

function Trig_InitLua_Actions()
    InitLua()
end

function InitTrig_InitLua()
gg_trg_InitLua = CreateTrigger()
TriggerRegisterTimerEventSingle(gg_trg_InitLua, 0.00)
TriggerAddAction(gg_trg_InitLua, Trig_InitLua_Actions)
end

function InitCustomTriggers()
InitTrig_InitLua()
end

function InitCustomPlayerSlots()
SetPlayerStartLocation(Player(0), 0)
ForcePlayerStartLocation(Player(0), 0)
SetPlayerColor(Player(0), ConvertPlayerColor(0))
SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(0), false)
SetPlayerController(Player(0), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(1), 1)
ForcePlayerStartLocation(Player(1), 1)
SetPlayerColor(Player(1), ConvertPlayerColor(1))
SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(1), false)
SetPlayerController(Player(1), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(2), 2)
ForcePlayerStartLocation(Player(2), 2)
SetPlayerColor(Player(2), ConvertPlayerColor(2))
SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(2), false)
SetPlayerController(Player(2), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(3), 3)
ForcePlayerStartLocation(Player(3), 3)
SetPlayerColor(Player(3), ConvertPlayerColor(3))
SetPlayerRacePreference(Player(3), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(3), false)
SetPlayerController(Player(3), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(4), 4)
ForcePlayerStartLocation(Player(4), 4)
SetPlayerColor(Player(4), ConvertPlayerColor(4))
SetPlayerRacePreference(Player(4), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(4), false)
SetPlayerController(Player(4), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(5), 5)
ForcePlayerStartLocation(Player(5), 5)
SetPlayerColor(Player(5), ConvertPlayerColor(5))
SetPlayerRacePreference(Player(5), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(5), false)
SetPlayerController(Player(5), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(11), 6)
SetPlayerColor(Player(11), ConvertPlayerColor(11))
SetPlayerRacePreference(Player(11), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(11), false)
SetPlayerController(Player(11), MAP_CONTROL_COMPUTER)
end

function InitCustomTeams()
SetPlayerTeam(Player(0), 0)
SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(1), 0)
SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(2), 0)
SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(3), 0)
SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(4), 0)
SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(5), 0)
SetPlayerState(Player(5), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(4), true)
SetPlayerTeam(Player(11), 1)
SetPlayerState(Player(11), PLAYER_STATE_ALLIED_VICTORY, 1)
end

function InitAllyPriorities()
SetStartLocPrioCount(0, 3)
SetStartLocPrio(0, 0, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 1, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 2, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(1, 2)
SetStartLocPrio(1, 0, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 1, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(2, 1)
SetStartLocPrio(2, 0, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(3, 2)
SetStartLocPrio(3, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 1, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(4, 3)
SetStartLocPrio(4, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 2, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(5, 3)
SetStartLocPrio(5, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 1, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 2, 4, MAP_LOC_PRIO_HIGH)
end

function main()
SetCameraBounds(-29184.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -32256.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 32256.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 29184.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -29184.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 29184.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 32256.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -32256.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
SetTerrainFogEx(0, 1000.0, 10000.0, 0.500, 1.000, 1.000, 0.588)
NewSoundEnvironment("Default")
SetAmbientDaySound("LordaeronSummerDay")
SetAmbientNightSound("LordaeronSummerNight")
SetMapMusic("Music", true, 0)
InitSounds()
CreateAllUnits()
InitBlizzard()
InitGlobals()
InitCustomTriggers()
end

function config()
SetMapName("TRIGSTR_167")
SetMapDescription("TRIGSTR_169")
SetPlayers(7)
SetTeams(7)
SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
DefineStartLocation(0, -23936.0, 5568.0)
DefineStartLocation(1, -23744.0, 3200.0)
DefineStartLocation(2, -24384.0, 4096.0)
DefineStartLocation(3, -24576.0, 6272.0)
DefineStartLocation(4, -24064.0, 4736.0)
DefineStartLocation(5, -24832.0, 5440.0)
DefineStartLocation(6, -24576.0, 5760.0)
InitCustomPlayerSlots()
InitCustomTeams()
InitAllyPriorities()
end

